const TREES = {
  career: {
    label: 'Career or job search',
    stages: ['Exploring possible directions', 'I know my target but am not positioned yet', 'Building skills or proof', 'Applying or networking', 'Interviewing or negotiating', 'Pursuing an internal move'],
    outcomes: ['Choose a clear target role', 'Build credible proof or a portfolio', 'Create a strong referral and interview pipeline', 'Reach final-round interviews', 'Land or negotiate a new role', 'Earn a promotion or internal move'],
    process: ['Research and shortlist high-fit roles', 'Build case studies or work samples', 'Have conversations with people in the field', 'Apply and follow up consistently', 'Practice interviews or presentations', 'Review conversion data and adjust'],
    beliefs: ['My background is not relevant enough', 'I need perfect credentials before I start', 'People will not respond to me', 'It is too late to change direction', 'Rejection means I am not qualified', 'I have to pursue every possible role'],
    evidence: ['Transferable results from past work', 'Colleagues, mentors or alumni', 'A portfolio, project or public work', 'Strong domain or customer knowledge', 'Time or budget for focused learning', 'Evidence that I have adapted before'],
    future: ['Focus on a small number of high-fit roles', 'Share work before it feels perfect', 'Make clear and respectful asks', 'Practice the hard part every week', 'Track the funnel instead of personalizing rejection', 'Protect focused job-search time'],
    actions: ['Target-role research', 'Resume or positioning work', 'Portfolio or case-study creation', 'Networking or referral outreach', 'Applications and follow-up', 'Interview or negotiation practice'],
    risks: ['An unclear or overly broad target', 'Perfectionism about materials', 'Avoiding outreach', 'Low response or application conversion', 'Weak interview preparation', 'Too many competing priorities'],
    firstWins: ['Choose 10 high-fit target roles', 'Finish one PM-style case study', 'Rewrite one strong career story', 'Contact five relevant people', 'Submit three high-fit applications', 'Complete two interview practices'],
    examples: {
      baseline: 'I have 10 years in product analytics but no PM title. My resume is updated, but I have not built a PM portfolio or started focused outreach.',
      goal: 'Build two PM case studies, have 15 conversations with product leaders, and reach three interview processes for product roles in tech.',
      process: 'Each week I research five roles, improve one proof point, contact five people and practice one product case.',
      belief: 'I notice the thought: “Without a PM title, hiring managers will not take me seriously.” It makes me avoid outreach and over-edit my resume.',
      evidence: 'I have already influenced roadmaps, led experiments and worked cross-functionally. A more accurate belief is: “I need to translate that evidence into a PM story and test it.”',
      future: 'My Day-90 self focuses on high-fit roles, asks for feedback early and treats response rates as data rather than a verdict.',
      firstWeek: 'Choose 10 high-fit PM roles, ask five relevant contacts for advice or referrals, and outline my first PM case study.',
    },
  },
  finances: {
    label: 'Money and finances',
    stages: ['I do not yet have a clear financial picture', 'I know the problem but lack a plan', 'I have a plan but follow it inconsistently', 'I am reducing debt or building savings', 'I am increasing income', 'I am preparing for a major financial decision'],
    outcomes: ['Build an emergency fund', 'Reduce a specific debt balance', 'Create and follow a spending plan', 'Increase monthly income', 'Make an informed investment decision', 'Prepare for a purchase or financial milestone'],
    process: ['Review accounts and categorize spending', 'Automate saving or debt payments', 'Complete one income-building action', 'Learn and compare options before deciding', 'Track one weekly financial metric', 'Hold a weekly money review'],
    beliefs: ['I am simply bad with money', 'It is too late to improve my finances', 'More income will solve every money problem', 'I must find the perfect investment', 'Looking at the numbers will make me feel worse', 'A setback means the plan failed'],
    evidence: ['Stable income or earning ability', 'Expenses I can realistically change', 'Savings, assets or unused resources', 'Financial knowledge or trusted guidance', 'Time for an income project', 'Past evidence of disciplined decisions'],
    future: ['Looks at the numbers without avoidance', 'Automates the important decision', 'Separates needs, values and impulses', 'Uses written criteria before investing', 'Reviews progress weekly', 'Adjusts the plan without abandoning it'],
    actions: ['Cash-flow review', 'Saving automation', 'Debt-repayment action', 'Income-growth action', 'Investment research', 'A financial conversation or decision'],
    risks: ['Avoiding account balances', 'Impulse spending', 'An unrealistic savings target', 'Taking more risk than I understand', 'Inconsistent tracking', 'An unexpected expense or income change'],
    firstWins: ['Calculate my current baseline', 'Set one automatic transfer', 'Make one extra debt payment', 'Cancel or reduce three expenses', 'Complete one income-building action', 'Write investment criteria before acting'],
    examples: {
      baseline: 'I save inconsistently and do not know my true monthly surplus. I have account data but no weekly review habit.',
      goal: 'Build a $6,000 emergency fund and automate a $500 weekly transfer by Day 90.',
      process: 'Every Friday I review spending, update one number and complete the next saving or income action.',
      belief: 'I notice the thought: “If I cannot fix everything quickly, there is no point starting.” That makes me avoid small, useful changes.',
      evidence: 'I have stable income and have saved successfully before. A more useful belief is: “A repeatable weekly system matters more than a perfect month.”',
      future: 'My Day-90 self checks the numbers calmly, automates priorities and pauses before taking financial risk.',
      firstWeek: 'Calculate my monthly baseline, identify three adjustable expenses and schedule the first automatic transfer.',
    },
  },
  relationships: {
    label: 'Relationships and social life',
    stages: ['New to an area or community', 'I have acquaintances but few close connections', 'I want to repair or deepen existing relationships', 'I want to date more intentionally', 'I socialize inconsistently', 'I need clearer boundaries or communication'],
    outcomes: ['Build a reliable local social circle', 'Deepen two or three friendships', 'Join communities where I belong', 'Create a healthy dating rhythm', 'Improve communication in a relationship', 'Set and maintain an important boundary'],
    process: ['Attend recurring groups or events', 'Initiate one-on-one follow-ups', 'Invite people to a specific plan', 'Practice honest communication', 'Make space for mutual support', 'Review which relationships feel reciprocal'],
    beliefs: ['People already have enough friends', 'I will seem needy if I initiate', 'Rejection means I am unlikeable', 'I need instant chemistry for a connection to matter', 'I am too busy to build relationships', 'Healthy boundaries will push people away'],
    evidence: ['Existing acquaintances or warm connections', 'Communities, faith groups or activities', 'Social skills I already use well', 'Time for recurring contact', 'People who have responded positively before', 'Values that help me choose healthy relationships'],
    future: ['Initiates without over-interpreting the response', 'Returns to the same communities consistently', 'Asks curious questions and follows up', 'Makes specific invitations', 'Chooses reciprocity over chasing', 'Communicates boundaries kindly and directly'],
    actions: ['Find recurring communities', 'Attend an event or gathering', 'Follow up with an acquaintance', 'Invite someone one-on-one', 'Have an honest conversation', 'Create a consistent social or dating routine'],
    risks: ['Waiting for others to initiate', 'Attending once but not returning', 'Taking a no personally', 'Choosing quantity over reciprocity', 'Overcommitting socially', 'Avoiding a needed conversation'],
    firstWins: ['Choose two recurring communities', 'Attend one relevant gathering', 'Follow up with three acquaintances', 'Make one specific invitation', 'Schedule one honest conversation', 'Set a weekly social block'],
    examples: {
      baseline: 'I recently moved to a new city. I know a few people through work and church, but most relationships have not moved beyond acquaintances.',
      goal: 'Build a healthier social life with two recurring communities and three people I see or speak with consistently by Day 90.',
      process: 'Each week I return to one group, follow up with two people and make one specific invitation.',
      belief: 'I notice the thought: “Everyone already has close friends, so they will not make room for me.” It makes me wait instead of following up.',
      evidence: 'People have responded warmly when I initiate. A more accurate belief is: “Some people are also looking for connection, and consistency will reveal who is reciprocal.”',
      future: 'My Day-90 self initiates warmly, returns consistently and invests in people who also make an effort.',
      firstWeek: 'Choose two recurring local groups, attend one event and invite one acquaintance to coffee or a walk.',
    },
  },
  health: {
    label: 'Health and energy',
    stages: ['I am deciding what to focus on', 'I am starting from a low or inconsistent baseline', 'I have a routine but cannot sustain it', 'I am progressing and want structure', 'I am returning after illness, injury or a setback', 'I need professional guidance before acting'],
    outcomes: ['Establish a consistent movement routine', 'Improve sleep or daily energy', 'Train for a specific event or capability', 'Build strength, mobility or endurance', 'Improve nutrition consistency', 'Complete appropriate professional evaluation or care'],
    process: ['Schedule repeatable movement sessions', 'Track sleep, energy or symptoms', 'Prepare food or environment in advance', 'Increase difficulty gradually', 'Use recovery and rest deliberately', 'Follow qualified professional guidance'],
    beliefs: ['If I miss a day, I have failed', 'A short session does not count', 'I need motivation before I begin', 'Progress should happen quickly', 'My past attempts prove I cannot stay consistent', 'Rest means I am losing momentum'],
    evidence: ['A routine or activity I already enjoy', 'Past periods of consistency', 'Access to a gym, equipment or safe space', 'A clinician, trainer or supportive person', 'Time blocks I can protect', 'Health data or a baseline I can track'],
    future: ['Chooses consistency over intensity', 'Uses minimum versions on busy days', 'Tracks a few useful signals', 'Adjusts for pain, illness or recovery', 'Prepares the environment in advance', 'Treats setbacks as information'],
    actions: ['Schedule movement', 'Measure a baseline', 'Prepare meals or environment', 'Improve sleep routine', 'Book professional support', 'Complete a safe first training session'],
    risks: ['Starting too aggressively', 'An all-or-nothing mindset', 'Low energy or poor sleep', 'Pain, illness or safety concerns', 'A schedule that is too ambitious', 'Not tracking what is working'],
    firstWins: ['Schedule three realistic sessions', 'Measure my starting baseline', 'Complete two short workouts', 'Create a consistent bedtime cue', 'Prepare three supportive meals', 'Book an appropriate professional appointment'],
    examples: {
      baseline: 'I exercise about once a week and sleep inconsistently. I enjoy strength training, but I lose the routine when work becomes busy.',
      goal: 'Complete three 30-minute strength sessions each week for 10 of the next 12 weeks and improve my average energy rating from 5 to 7.',
      process: 'I train Monday, Thursday and Saturday, use a 10-minute minimum version on busy days, and review energy every Sunday.',
      belief: 'I notice the thought: “If I cannot complete the full workout, it is not worth starting.” That turns one busy day into a lost week.',
      evidence: 'I enjoy strength training and have been consistent before. A better belief is: “The minimum version protects the identity and routine.”',
      future: 'My Day-90 self plans around real energy, starts small and adjusts without turning a missed day into failure.',
      firstWeek: 'Schedule three sessions, complete two 20-minute workouts and record my sleep and energy baseline.',
    },
  },
  launch: {
    label: 'Business or creative launch',
    stages: ['Exploring ideas', 'I have an idea but no validated problem', 'Building a first version', 'Testing with early users', 'Trying to grow usage or revenue', 'Preparing to launch publicly'],
    outcomes: ['Validate a specific customer problem', 'Build a usable first version', 'Recruit and learn from early users', 'Launch publicly', 'Reach a usage or revenue milestone', 'Choose whether to continue, change or stop'],
    process: ['Interview potential users', 'Build the smallest useful version', 'Recruit testers directly', 'Observe usage and collect feedback', 'Improve the activation or retention path', 'Share the product consistently'],
    beliefs: ['The product must look perfect before people see it', 'No response means the idea is bad', 'I need a large audience to start', 'I should add more features before testing', 'Charging money will drive everyone away', 'Changing direction means I failed'],
    evidence: ['Relevant domain experience', 'Potential users I can reach', 'A prototype or existing product', 'Technical or creative skills', 'A partner, advisor or community', 'Early usage, feedback or revenue'],
    future: ['Talks to users before building more', 'Ships small improvements frequently', 'Makes direct recruiting asks', 'Measures activation and return behavior', 'Separates feedback from commands', 'Changes tactics when evidence changes'],
    actions: ['Customer interviews', 'Prototype or product work', 'Early-user recruiting', 'Onboarding improvement', 'Feedback analysis', 'Launch or distribution work'],
    risks: ['Building without user evidence', 'Adding too many features', 'Avoiding direct recruiting', 'Listening only to compliments', 'No clear activation metric', 'Changing direction too often'],
    firstWins: ['Define one narrow user and problem', 'Interview five potential users', 'Ship one usable workflow', 'Recruit five early testers', 'Observe three onboarding sessions', 'Choose one activation metric'],
    examples: {
      baseline: 'I have a working product and a bootcamp audience I can reach, but few people have used it long enough to give behavioral feedback.',
      goal: 'Recruit 30 qualified early users, get 15 to create a plan, and have five return for a weekly check-in by Day 90.',
      process: 'Each week I recruit users directly, watch where they stop, interview two users and improve one activation bottleneck.',
      belief: 'I notice the thought: “If friends are not interested, the product must not be useful.” That makes me redesign before testing with the right audience.',
      evidence: 'I can reach a relevant bootcamp audience and already have a working flow. A better belief is: “Qualified-user behavior is more useful evidence than general encouragement.”',
      future: 'My Day-90 self recruits directly, watches behavior and makes one evidence-based product decision at a time.',
      firstWeek: 'Recruit five qualified users, watch three complete onboarding sessions and record the first major drop-off.',
    },
  },
  wellbeing: {
    label: 'Personal growth and wellbeing',
    stages: ['I feel unclear about what needs attention', 'I understand the pattern but repeat it', 'I am beginning a new practice', 'I am rebuilding after a difficult period', 'I have support and want more consistency', 'I need qualified professional support'],
    outcomes: ['Create a consistent reflection practice', 'Reduce avoidance around a recurring situation', 'Build a calmer daily routine', 'Make and act on an important decision', 'Strengthen confidence through action', 'Find appropriate professional or community support'],
    process: ['Notice thoughts, emotions and body signals', 'Journal or reflect consistently', 'Practice a different response', 'Take one values-aligned action', 'Use supportive relationships', 'Review patterns without self-attack'],
    beliefs: ['I should be over this already', 'My feelings mean I cannot act', 'I need certainty before deciding', 'Being kind to myself will make me less accountable', 'Other people are progressing faster', 'One setback erases my progress'],
    evidence: ['Times I handled difficulty before', 'A therapist, coach, faith or support community', 'A reflection or spiritual practice', 'Values that clarify my decisions', 'People who know me well', 'Time and space I can protect'],
    future: ['Notices without immediately reacting', 'Names the need beneath the pattern', 'Chooses a believable response', 'Acts before certainty is complete', 'Asks for support appropriately', 'Reviews progress with compassion and honesty'],
    actions: ['Daily reflection', 'A grounding or meditation practice', 'One avoided conversation or task', 'A values-based decision', 'Reach out for support', 'Create a supportive routine'],
    risks: ['Using reflection instead of action', 'Harsh self-criticism', 'Avoiding uncomfortable feelings', 'Waiting for certainty', 'Isolating instead of asking for support', 'Expecting linear progress'],
    firstWins: ['Complete three short reflections', 'Practice one new response twice', 'Take one avoided action', 'Schedule a supportive conversation', 'Write decision criteria', 'Book qualified support if needed'],
    examples: {
      baseline: 'I understand that self-doubt and overthinking slow me down, but I do not yet have a consistent way to notice the pattern and choose a response.',
      goal: 'Use a 10-minute reflection practice four days a week and complete one previously avoided action each week for 12 weeks.',
      process: 'I pause, name what I notice and need, choose one believable response, then take a small action before continuing to reflect.',
      belief: 'I notice the thought: “I must feel confident before I act.” It keeps confidence dependent on mood rather than evidence.',
      evidence: 'I have acted effectively while uncertain before. A better belief is: “Confidence can follow a small, values-aligned action.”',
      future: 'My Day-90 self makes room for feelings without letting them make every decision.',
      firstWeek: 'Complete three 10-minute reflections and take one action I have been postponing.',
    },
  },
  other: {
    label: 'Something else',
    stages: ['I am still defining the goal', 'I know the goal but have not started', 'I started without a clear plan', 'I am acting inconsistently', 'I am making progress but need structure', 'I am restarting after a setback'],
    outcomes: ['Make a clear decision', 'Finish a concrete deliverable', 'Reach a measurable milestone', 'Build a consistent practice', 'Create a new opportunity', 'Test whether this direction is right'],
    process: ['Research and choose priorities', 'Practice or build consistently', 'Ask relevant people for input', 'Create and share evidence', 'Track one useful metric', 'Review progress and adjust weekly'],
    beliefs: ['I need certainty before I start', 'I am not ready or qualified enough', 'A small action will not matter', 'Other people will judge the attempt', 'A setback means I chose the wrong goal', 'I have to follow the original route'],
    evidence: ['Relevant experience or skills', 'People who can help', 'Existing work or resources', 'Time I can protect', 'Past evidence of persistence', 'Access to useful tools or guidance'],
    future: ['Focuses on one priority', 'Acts before everything is perfect', 'Asks for useful feedback', 'Practices consistently', 'Tracks evidence rather than mood', 'Adjusts the route without abandoning the intention'],
    actions: ['Research or planning', 'Create or practice', 'Reach out to people', 'Share or test something', 'Track a baseline', 'Make a decision'],
    risks: ['An unclear target', 'Perfectionism or overthinking', 'Avoidance or procrastination', 'Too many priorities', 'Limited support', 'Ignoring useful feedback'],
    firstWins: ['Define a measurable target', 'Finish a first draft', 'Contact three relevant people', 'Complete two practice sessions', 'Measure the starting baseline', 'Schedule the next three actions'],
    examples: {
      baseline: 'I have a general direction and some relevant experience, but I have not defined a measurable result or repeatable weekly process.',
      goal: 'Complete a specific, observable milestone by Day 90 and create evidence that tells me what to do next.',
      process: 'Each week I complete one meaningful action, collect feedback and decide the next small experiment.',
      belief: 'I notice the thought: “I need the entire path before I begin.” It turns planning into avoidance.',
      evidence: 'I have learned through action before. A better belief is: “The next useful step can create information the plan cannot predict.”',
      future: 'My Day-90 self acts consistently, uses feedback and stays flexible about the route.',
      firstWeek: 'Define the outcome, measure my baseline and complete the first observable action.',
    },
  },
};

const ALIASES = {
  'career breakthrough': 'career', career: 'career',
  'financial progress': 'finances', 'money and finances': 'finances', finances: 'finances',
  'relationships and social connection': 'relationships', 'relationships and social life': 'relationships', relationships: 'relationships',
  'health and energy': 'health', health: 'health',
  'launching something of my own': 'launch', 'business or creative launch': 'launch', launch: 'launch',
  'personal growth and inner wellbeing': 'wellbeing', 'personal growth and wellbeing': 'wellbeing', wellbeing: 'wellbeing',
  'something else': 'other', other: 'other',
};

export function getOnboardingTree(category) {
  const normalized = String(category || '').trim().toLowerCase();
  const key = TREES[normalized] ? normalized : (ALIASES[normalized] || 'other');
  return { key, ...TREES[key] };
}

